# Version 0.0.5
# Date: 2023-01-07
# Author: mytechtoday@protonmail.com
# Description: Docker Compose file for local development
# Usage: docker-compose -f compose-dev.yaml up -d
#        docker-compose -f compose-dev.yaml down
#        docker-compose -f compose-dev.yaml logs -f
#        docker-compose -f compose-dev.yaml exec db bash
#        docker-compose -f compose-dev.yaml exec wordpress bash
#        docker-compose -f compose-dev.yaml exec db mysql -u root -p
#        docker-compose -f compose-dev.yaml exec db mysql -u wordpress -pwordpress
#        docker-compose -f compose-dev.yaml exec db mysql -u wordpress -pwordpress wordpress
#       docker-compose -f compose-dev.yaml exec db mysql -u wordpress -pwordpress wordpress -e "SELECT * FROM wp_options WHERE option_name = 'siteurl' OR option_name = 'home';"
#       docker-compose -f compose-dev.yaml exec db mysql -u wordpress -pwordpress wordpress -e "UPDATE wp_options SET option_value = 'http://localhost:8000' WHERE option_name = 'siteurl' OR option_name = 'home';"
#      docker-compose -f compose-dev.yaml exec db mysql -u wordpress -pwordpress wordpress -e "SELECT * FROM wp_options WHERE option_name = 'siteurl' OR option_name = 'home';"

version: '3.8'

services:
  # MySQL Service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    restart: always

  # WordPress Service
  wordpress:
    depends_on:
      - db
    image: 6.4.2-php8.1-apache
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugins/im-meme-player:/var/www/html/wp-content/plugins/im-meme-player
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data: {}
