version: '3.8'

services:
  # MySQL Service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    restart: always

  # WordPress Service
  wordpress:
    depends_on:
      - db
    image: wordpress:6.4-php7.4-apache
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugins/im-meme-player:/var/www/html/wp-content/plugins/im-meme-player
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data: {}
